# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Emotion_Detection_CNN-main\emotion_detector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from empa import Ui_empa
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_detect(QMainWindow):
    def setupUi(self, Form):
        super().__init__()

        Form.setObjectName("Form")
        Form.resize(839, 692)
        Form.setStyleSheet("font: 18pt \"Century Gothic\";"
                           "\n"
                           "background-image: url(\"C:/Emotion_Detection_CNN-main/fon.png\");\n"
                           "background-position: center;")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 180, 461, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setStyleSheet("background-color: rgb(114, 222, 255);")
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.go_to_empa)
        # Подключение кнопки, чтобы открыть Эмпа

        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(114, 222, 255);")
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Empa", "Empa"))
        self.pushButton.setText(_translate("Empa", "Вход"))
        self.pushButton_2.setText(_translate("Empa", "Регистрация"))

    # Функция переход к empa
    def go_to_empa(self):
        # задать класс window_empa
        self.window_empa = QtWidgets.QWidget()
        ui = Ui_empa()
        # установка UI в window_empa
        ui.setupUi(self.window_empa)
        # прячем основное окно
        Form.hide()
        # показываем empa
        self.window_empa.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_detect()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
