# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Emotion_Detection_CNN-main\empa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QWidget


class Ui_empa(QMainWindow):
    def setupUi(self, Form):
        super().__init__()

        Form.setObjectName("Form")
        Form.resize(837, 740)
        Form.setStyleSheet("font: 75 48pt \"Century Gothic\";" "background-color: ;\n")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(290, 110, 311, 241))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 609, 751, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("font: 9pt \"Century Gothic\";\n"
                                        "font: 14pt \"MS Shell Dlg 2\";"
                                        "background-color: rgb(181, 181, 181);\n"
                                        "border-radius: 10px;"
                                        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("font: 9pt \"Century Gothic\";\n"
                                        "font: 14pt \"MS Shell Dlg 2\";"
                                        "background-color: rgb(149, 213, 178);\n"
                                        "border-radius: 10px;"
                                        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_4.clicked.connect(lambda: self.launch_trainig())
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 9pt \"Century Gothic\";\n"
                                        "font: 14pt \"MS Shell Dlg 2\";"
                                        "background-color: rgb(114, 222, 255);\n"
                                        "border-radius: 10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(225, 500, 381, 91))
        self.pushButton.setStyleSheet("font: 16pt \"Century Gothic\";\n"
                                      "background-color: rgb(255, 170, 0);\n"
                                      "border-radius: 20px;")
        self.pushButton.setObjectName("pushButton")

        # лямбда функция чтобы запустить main.py
        self.pushButton.clicked.connect(lambda: self.launch_main_py())

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(240, 50, 381, 71))
        self.lineEdit.setStyleSheet("font: 18pt \"Century Gothic\";"
                                    "border-radius: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(290, 270, 241, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(290, 270, 241, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(290, 180, 241, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 330, 421, 81))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def launch_trainig(self):
        os.chdir("C:\Emotion_Detection_CNN-main")
        os.system(r'.\venv\Scripts\activate && python ./Emotion_Detection_CNN-main/training_connect.py')
    def launch_main_py(self):
        os.chdir("C:\Emotion_Detection_CNN-main")
        os.system(r'.\venv\Scripts\activate && python ./Emotion_Detection_CNN-main/main.py')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Empa", "Empa"))
        self.label.setText(_translate("Empa", "Эмпа"))
        self.pushButton_2.setText(_translate("Empa", "Карты пациентов"))
        self.pushButton_3.setText(_translate("Empa", "Пройти опрос"))
        self.pushButton_4.setText(_translate("Empa", "Тренировка"))
        self.pushButton.setText(_translate("Empa", "Отслеживание эмоций"))
        self.lineEdit.setText(_translate("Empa", "Поиск"))
        self.label_2.setText(_translate("Empa",
                                        "<html><head/><body><p><span style=\" font-size:28pt; font-weight:400; text-decoration: ; vertical-align:super;\">Ваши эмоции нам открыты</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_empa()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
